account: 
  secret_token :  f0bdf5df7e9ed5f97736eb997e9ac61886d559670fbb2def8f46b7c40613023404cf88363d38321d5540d
  id : 1601083832

link :
  link_url : vkpeople.ru
  link_domain : vkpeople.ru

country : 1

sex:
  man : 1
  woman : 2
  # TODO in model method get_statistics
  # man_and_woman : 0  

# если  age=0 значит возраст не задан
age : 
  from : 1 
  to : 100
